# 配置文件

# 数据配置
data:
  data_dir: "data"
  test_ratio: 0.2
  val_ratio: 0.1
  negative_sampling_ratio: 0.5  # 负样本与正样本的比例
  target_relations:  # 目标关系类型
    - "indication"

# 模型配置
model:
  hidden_dim: 256
  num_layers: 3
  dropout: 0.1
  num_bases: null  # 如果为null，则不使用basis decomposition
  num_blocks: null  # 如果为null，则不使用block decomposition
  # --- 新增 MLP 配置 ---
  link_predictor:
    type: "mlp" # 或 "l2" 用于切换回旧版本
    mlp_hidden_dim: 256 # 可以等于或不等于 hidden_dim
    mlp_layers: 2
    dropout: 0.1 # 可以复用 model.dropout 或单独设置

# 训练配置
training:
  batch_size: 512
  learning_rate: 0.001
  weight_decay: 0.00001
  num_epochs: 200
  patience: 50  # early stopping patience
  gradient_clip: 1.0
  
  # 学习率调度
  scheduler:
    type: "ReduceLROnPlateau"  # StepLR, ExponentialLR, ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.000001
  
  # 损失函数配置
  loss:
    type: "clip" # "clip" # 或 "bce_ce" (用于回退测试)
    clip_temperature: 0.07

# 评估配置
evaluation:
  mode: "cross_disease" # 添加或修改这一行
  metrics:
    - "auc"
    - "ap"
    - "precision_at_k"
    - "recall_at_k"
  k_values: [10, 50, 100]
# 设备配置
device: "auto"  # cuda, cpu, auto

# 日志配置
logging:
  log_dir: "logs"
  save_model: true
  model_dir: "checkpoints"
  log_interval: 10  # 每多少个batch记录一次
  
# 随机种子
seed: 42

# 实验配置
experiment:
  name: "drugdisease_rgcn"
  description: "Drug-Disease relation prediction using RGCN on PrimeKG"
  tags:
    - "rgcn"
    - "primekg"
    - "drug-disease"
    - "link-prediction"